config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  post '/custom_sign_up', to: "omniauth_callbacks#custom_sign_up"

  root 'main#home'
  get '/completar_registro', to: "main#edit"

  get '/inscribir', to: "main#inscripcion"
  get '/unirse', to: "main#unirse"
  post '/check_ticket', to: "main#check_ticket"
  post '/create_ticket', to: "main#crear_ticket"
  get '/bases', to: "main#bases"
  get '/generar', to: "main#generar"
  
  resources :teams do
    resources :players
  end

end

app/views/layouts/application.haml
%html
	%head
		%title Torneo de Dota
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0" }
		=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		=javascript_include_tag 'application', 'data-turbolinks-track' => true
		=csrf_meta_tags
	%body
		%nav
			%div{ :class => "nav-wrapper grey darken-4"}
				%a{:href => "/", :class => "brand-logo"}
					%img{:id => "logo" ,:class =>"valign responsive-img",src: "http://i.imgur.com/3DTThZz.png"}
				%a{:href => "#", "data-activates" => "mobile-demo" , :class => "button-collapse"}
					%i{:class => "material-icons"}menu
				%ul{:class => "right hide-on-med-and-down"}
					%li
						=link_to "Inicio", root_path
					%li
						=link_to "Equipos", teams_path
					%li
						=link_to "Bases del Torneo", bases_path
					-if !user_signed_in?
						%li
							=link_to "Inscribir", inscribir_path
						%li
							=link_to "Unirse a Equipo", unirse_path
					-if user_signed_in?
						-unless current_user.team_id.nil?
							%li
								=link_to "TEAM: #{current_user.team.name}", team_path(current_user.team_id)
						-else
							%li
								=link_to "Inscribir", inscribir_path
							%li
								=link_to "Unirse a Equipo", unirse_path
						-if current_user.is_admin?
							%li
								=link_to "Generar KEY", generar_path
						-if current_user.image.empty?
							%li
								%img{:class => "circle responsive-img" ,src: "https://www.fanspole.com/assets/default_user-c283cfbc3d432e22b1d2f1eef515d0b9.png", width: "25", height: "25"}
						-else
							%li
								=image_tag(current_user.image, class: "circle responsive-img", id: "me-logo")
						%li
							=link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "btn red darken-4"
					-else
						%li
							=link_to "Registrate", user_facebook_omniauth_authorize_path, class: "aves-effect waves-light btn indigo darken-4"
				%ul{:class => "side-nav", :id => "mobile-demo"}
					%li
						=link_to "Inicio", root_path
					%li
						=link_to "Equipos", teams_path
					%li
						=link_to "Bases del Torneo", bases_path
					-if !user_signed_in?
						%li
							=link_to "Inscribir", inscribir_path
						%li
							=link_to "Unirse a Equipo", unirse_path
					-if user_signed_in?
						-unless current_user.team_id.nil?
							%li
								=link_to "TEAM: #{current_user.team.name}", team_path(current_user.team_id)
						-else
							%li
								=link_to "Inscribir", inscribir_path
							%li
								=link_to "Unirse a Equipo", unirse_path
						-if current_user.is_admin?
							%li
								=link_to "Generar KEY", generar_path
						-if current_user.image.empty?
							%li
								%img{:class => "circle responsive-img" ,src: "https://www.fanspole.com/assets/default_user-c283cfbc3d432e22b1d2f1eef515d0b9.png", width: "25", height: "25"}
						-else
							%li
								=image_tag(current_user.image, class: "circle responsive-img", id: "me-logo")
						%li
							=link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "btn red darken-4"
					-else
						%li
							=link_to "Registrate", user_facebook_omniauth_authorize_path, class: "aves-effect waves-light btn indigo darken-4"

	=react_component 'NavMain'
	%div{style:" #{"display:none;" if alert.nil? && notice.nil?} "}
		%p.notice= notice
		%p.alert= alert
	= yield